"""sync_missing_columns

Revision ID: 7b92f34cdc67
Revises: 008
Create Date: 2026-09-19 17:09:15.561263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7b92f34cdc67'
down_revision: Union[str, None] = '008'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profiles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('xp', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('solved_count', sa.Integer(), nullable=False),
    sa.Column('total_submissions', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profiles_level'), 'profiles', ['level'], unique=False)
    op.create_index(op.f('ix_profiles_username'), 'profiles', ['username'], unique=True)
    op.create_index(op.f('ix_profiles_xp'), 'profiles', ['xp'], unique=False)
    op.create_table('discussions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('problem_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('upvotes', sa.Integer(), nullable=False),
    sa.Column('is_solution', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['discussions.id'], ),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discussions_id'), 'discussions', ['id'], unique=False)
    op.create_index(op.f('ix_discussions_problem_id'), 'discussions', ['problem_id'], unique=False)
    op.create_index(op.f('ix_discussions_user_id'), 'discussions', ['user_id'], unique=False)
    op.create_table('discussion_votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('discussion_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('vote', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['discussion_id'], ['discussions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('discussion_id', 'user_id', name='uq_discussion_vote')
    )
    op.create_index(op.f('ix_discussion_votes_discussion_id'), 'discussion_votes', ['discussion_id'], unique=False)
    op.create_index(op.f('ix_discussion_votes_id'), 'discussion_votes', ['id'], unique=False)
    op.create_index(op.f('ix_discussion_votes_user_id'), 'discussion_votes', ['user_id'], unique=False)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_level'), table_name='users')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_xp'), table_name='users')
    op.drop_table('users')
    op.alter_column('achievements', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_achievements_id'), 'achievements', ['id'], unique=False)
    op.alter_column('ai_conversations', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('ai_conversations', 'task_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('ai_conversations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('ai_conversations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_ai_conversations_id'), 'ai_conversations', ['id'], unique=False)
    op.drop_constraint(op.f('ai_conversations_user_id_fkey'), 'ai_conversations', type_='foreignkey')
    op.create_foreign_key(None, 'ai_conversations', 'profiles', ['user_id'], ['id'])
    op.alter_column('ai_feedback', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('ai_feedback', 'comment',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("''::text"))
    op.alter_column('ai_feedback', 'task_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('ai_feedback', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_ai_feedback_id'), 'ai_feedback', ['id'], unique=False)
    op.drop_constraint(op.f('ai_feedback_user_id_fkey'), 'ai_feedback', type_='foreignkey')
    op.create_foreign_key(None, 'ai_feedback', 'profiles', ['user_id'], ['id'])
    op.alter_column('ai_messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_ai_messages_id'), 'ai_messages', ['id'], unique=False)
    op.create_index(op.f('ix_concepts_id'), 'concepts', ['id'], unique=False)
    op.create_index(op.f('ix_learning_modules_id'), 'learning_modules', ['id'], unique=False)
    op.alter_column('learning_paths', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('learning_paths', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_learning_paths_id'), 'learning_paths', ['id'], unique=False)
    op.create_index(op.f('ix_lesson_prerequisites_id'), 'lesson_prerequisites', ['id'], unique=False)
    op.alter_column('lesson_progress', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
    op.create_index(op.f('ix_lesson_progress_id'), 'lesson_progress', ['id'], unique=False)
    op.drop_constraint(op.f('lesson_progress_user_id_fkey'), 'lesson_progress', type_='foreignkey')
    op.create_foreign_key(None, 'lesson_progress', 'profiles', ['user_id'], ['id'])
    op.create_index(op.f('ix_lessons_id'), 'lessons', ['id'], unique=False)
    op.create_index(op.f('ix_problem_concepts_id'), 'problem_concepts', ['id'], unique=False)
    op.add_column('problems', sa.Column('time_complexity', sa.String(length=50), nullable=False))
    op.add_column('problems', sa.Column('space_complexity', sa.String(length=50), nullable=False))
    op.add_column('problems', sa.Column('reference_solution', sa.Text(), nullable=False))
    op.alter_column('problems', 'slug',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('problems', 'title',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('problems', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('problems', 'difficulty',
               existing_type=postgresql.ENUM('EASY', 'MEDIUM', 'HARD', name='difficulty'),
               nullable=False)
    op.alter_column('problems', 'category',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('problems', 'language',
               existing_type=postgresql.ENUM('VERILOG', 'SYSTEMVERILOG', name='language'),
               nullable=False)
    op.alter_column('problems', 'input_description',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("''::text"))
    op.alter_column('problems', 'output_description',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("''::text"))
    op.alter_column('problems', 'constraints',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("''::text"))
    op.alter_column('problems', 'starter_code',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("''::text"))
    op.alter_column('problems', 'test_cases',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("''::text"))
    op.alter_column('problems', 'time_limit',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('5'))
    op.alter_column('problems', 'memory_limit',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('256'))
    op.alter_column('problems', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('problems', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('quiz_attempts', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('quiz_attempts', 'attempted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_quiz_attempts_id'), 'quiz_attempts', ['id'], unique=False)
    op.drop_constraint(op.f('quiz_attempts_user_id_fkey'), 'quiz_attempts', type_='foreignkey')
    op.create_foreign_key(None, 'quiz_attempts', 'profiles', ['user_id'], ['id'])
    op.create_index(op.f('ix_quiz_questions_id'), 'quiz_questions', ['id'], unique=False)
    op.create_index(op.f('ix_quizzes_id'), 'quizzes', ['id'], unique=False)
    op.alter_column('submission_test_results', 'submission_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('submission_test_results', 'test_case_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('submission_test_results', 'test_name',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('submission_test_results', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('submission_test_results', 'score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text("'0'::double precision"))
    op.alter_column('submission_test_results', 'message',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("''::text"))
    op.alter_column('submission_test_results', 'expected',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("''::text"))
    op.alter_column('submission_test_results', 'actual',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("''::text"))
    op.add_column('submissions', sa.Column('user_id', sa.String(), nullable=True))
    op.alter_column('submissions', 'problem_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('submissions', 'code',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('submissions', 'language',
               existing_type=postgresql.ENUM('VERILOG', 'SYSTEMVERILOG', name='language'),
               nullable=False)
    op.alter_column('submissions', 'status',
               existing_type=postgresql.ENUM('QUEUED', 'RUNNING', 'PASSED', 'PARTIAL', 'FAILED', 'COMPILATION_ERROR', 'RUNTIME_ERROR', 'TIME_LIMIT_EXCEEDED', 'MEMORY_LIMIT_EXCEEDED', 'OUTPUT_LIMIT_EXCEEDED', 'INVALID_SUBMISSION', 'JUDGE_ERROR', 'SYSTEM_ERROR', name='submissionstatus'),
               nullable=False)
    op.alter_column('submissions', 'score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text("'0'::double precision"))
    op.alter_column('submissions', 'tests_passed',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('submissions', 'tests_total',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('submissions', 'execution_time',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text("'0'::double precision"))
    op.alter_column('submissions', 'compilation_message',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("''::text"))
    op.alter_column('submissions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_submissions_user_id'), 'submissions', ['user_id'], unique=False)
    op.create_foreign_key(None, 'submissions', 'profiles', ['user_id'], ['id'])
    op.alter_column('test_cases', 'problem_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('test_cases', 'name',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('test_cases', 'description',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("''::text"))
    op.alter_column('test_cases', 'testbench',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('test_cases', 'visibility',
               existing_type=postgresql.ENUM('PUBLIC', 'HIDDEN', name='testvisibility'),
               nullable=False)
    op.alter_column('test_cases', 'weight',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text("'1'::double precision"))
    op.alter_column('test_cases', 'execution_order',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('test_cases', 'enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('test_cases', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('test_cases', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_achievements', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('user_achievements', 'unlocked_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_user_achievements_id'), 'user_achievements', ['id'], unique=False)
    op.drop_constraint(op.f('user_achievements_user_id_fkey'), 'user_achievements', type_='foreignkey')
    op.create_foreign_key(None, 'user_achievements', 'profiles', ['user_id'], ['id'])
    op.alter_column('user_concept_progress', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
    op.create_index(op.f('ix_user_concept_progress_id'), 'user_concept_progress', ['id'], unique=False)
    op.drop_constraint(op.f('user_concept_progress_user_id_fkey'), 'user_concept_progress', type_='foreignkey')
    op.create_foreign_key(None, 'user_concept_progress', 'profiles', ['user_id'], ['id'])
    op.alter_column('user_problem_progress', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('user_problem_progress', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_problem_progress', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_user_problem_progress_id'), 'user_problem_progress', ['id'], unique=False)
    op.drop_constraint(op.f('user_problem_progress_user_id_fkey'), 'user_problem_progress', type_='foreignkey')
    op.create_foreign_key(None, 'user_problem_progress', 'profiles', ['user_id'], ['id'])
    op.alter_column('waveforms', 'submission_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('waveforms', 'waveform_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('waveforms', 'format',
               existing_type=sa.VARCHAR(length=10),
               nullable=False,
               existing_server_default=sa.text("'vcd'::character varying"))
    op.alter_column('waveforms', 'file_size',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('waveforms', 'duration',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('waveforms', 'timescale',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'1ns'::character varying"))
    op.alter_column('waveforms', 'signal_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('waveforms', 'file_path',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("''::text"))
    op.alter_column('waveforms', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('waveforms', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('waveforms', 'file_path',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("''::text"))
    op.alter_column('waveforms', 'signal_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('waveforms', 'timescale',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'1ns'::character varying"))
    op.alter_column('waveforms', 'duration',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('waveforms', 'file_size',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('waveforms', 'format',
               existing_type=sa.VARCHAR(length=10),
               nullable=True,
               existing_server_default=sa.text("'vcd'::character varying"))
    op.alter_column('waveforms', 'waveform_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('waveforms', 'submission_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'user_problem_progress', type_='foreignkey')
    op.create_foreign_key(op.f('user_problem_progress_user_id_fkey'), 'user_problem_progress', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_user_problem_progress_id'), table_name='user_problem_progress')
    op.alter_column('user_problem_progress', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_problem_progress', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_problem_progress', 'user_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'user_concept_progress', type_='foreignkey')
    op.create_foreign_key(op.f('user_concept_progress_user_id_fkey'), 'user_concept_progress', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_user_concept_progress_id'), table_name='user_concept_progress')
    op.alter_column('user_concept_progress', 'user_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'user_achievements', type_='foreignkey')
    op.create_foreign_key(op.f('user_achievements_user_id_fkey'), 'user_achievements', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_user_achievements_id'), table_name='user_achievements')
    op.alter_column('user_achievements', 'unlocked_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_achievements', 'user_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('test_cases', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('test_cases', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('test_cases', 'enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('test_cases', 'execution_order',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('test_cases', 'weight',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text("'1'::double precision"))
    op.alter_column('test_cases', 'visibility',
               existing_type=postgresql.ENUM('PUBLIC', 'HIDDEN', name='testvisibility'),
               nullable=True)
    op.alter_column('test_cases', 'testbench',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('test_cases', 'description',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("''::text"))
    op.alter_column('test_cases', 'name',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('test_cases', 'problem_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'submissions', type_='foreignkey')
    op.drop_index(op.f('ix_submissions_user_id'), table_name='submissions')
    op.alter_column('submissions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('submissions', 'compilation_message',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("''::text"))
    op.alter_column('submissions', 'execution_time',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text("'0'::double precision"))
    op.alter_column('submissions', 'tests_total',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('submissions', 'tests_passed',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('submissions', 'score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text("'0'::double precision"))
    op.alter_column('submissions', 'status',
               existing_type=postgresql.ENUM('QUEUED', 'RUNNING', 'PASSED', 'PARTIAL', 'FAILED', 'COMPILATION_ERROR', 'RUNTIME_ERROR', 'TIME_LIMIT_EXCEEDED', 'MEMORY_LIMIT_EXCEEDED', 'OUTPUT_LIMIT_EXCEEDED', 'INVALID_SUBMISSION', 'JUDGE_ERROR', 'SYSTEM_ERROR', name='submissionstatus'),
               nullable=True)
    op.alter_column('submissions', 'language',
               existing_type=postgresql.ENUM('VERILOG', 'SYSTEMVERILOG', name='language'),
               nullable=True)
    op.alter_column('submissions', 'code',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('submissions', 'problem_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('submissions', 'user_id')
    op.alter_column('submission_test_results', 'actual',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("''::text"))
    op.alter_column('submission_test_results', 'expected',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("''::text"))
    op.alter_column('submission_test_results', 'message',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("''::text"))
    op.alter_column('submission_test_results', 'score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text("'0'::double precision"))
    op.alter_column('submission_test_results', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('submission_test_results', 'test_name',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('submission_test_results', 'test_case_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('submission_test_results', 'submission_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_quizzes_id'), table_name='quizzes')
    op.drop_index(op.f('ix_quiz_questions_id'), table_name='quiz_questions')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'quiz_attempts', type_='foreignkey')
    op.create_foreign_key(op.f('quiz_attempts_user_id_fkey'), 'quiz_attempts', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_quiz_attempts_id'), table_name='quiz_attempts')
    op.alter_column('quiz_attempts', 'attempted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('quiz_attempts', 'user_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('problems', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('problems', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('problems', 'memory_limit',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('256'))
    op.alter_column('problems', 'time_limit',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('5'))
    op.alter_column('problems', 'test_cases',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("''::text"))
    op.alter_column('problems', 'starter_code',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("''::text"))
    op.alter_column('problems', 'constraints',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("''::text"))
    op.alter_column('problems', 'output_description',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("''::text"))
    op.alter_column('problems', 'input_description',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("''::text"))
    op.alter_column('problems', 'language',
               existing_type=postgresql.ENUM('VERILOG', 'SYSTEMVERILOG', name='language'),
               nullable=True)
    op.alter_column('problems', 'category',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('problems', 'difficulty',
               existing_type=postgresql.ENUM('EASY', 'MEDIUM', 'HARD', name='difficulty'),
               nullable=True)
    op.alter_column('problems', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('problems', 'title',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('problems', 'slug',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_column('problems', 'reference_solution')
    op.drop_column('problems', 'space_complexity')
    op.drop_column('problems', 'time_complexity')
    op.drop_index(op.f('ix_problem_concepts_id'), table_name='problem_concepts')
    op.drop_index(op.f('ix_lessons_id'), table_name='lessons')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'lesson_progress', type_='foreignkey')
    op.create_foreign_key(op.f('lesson_progress_user_id_fkey'), 'lesson_progress', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_lesson_progress_id'), table_name='lesson_progress')
    op.alter_column('lesson_progress', 'user_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_index(op.f('ix_lesson_prerequisites_id'), table_name='lesson_prerequisites')
    op.drop_index(op.f('ix_learning_paths_id'), table_name='learning_paths')
    op.alter_column('learning_paths', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('learning_paths', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_learning_modules_id'), table_name='learning_modules')
    op.drop_index(op.f('ix_concepts_id'), table_name='concepts')
    op.drop_index(op.f('ix_ai_messages_id'), table_name='ai_messages')
    op.alter_column('ai_messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'ai_feedback', type_='foreignkey')
    op.create_foreign_key(op.f('ai_feedback_user_id_fkey'), 'ai_feedback', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_ai_feedback_id'), table_name='ai_feedback')
    op.alter_column('ai_feedback', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('ai_feedback', 'task_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('ai_feedback', 'comment',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("''::text"))
    op.alter_column('ai_feedback', 'user_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'ai_conversations', type_='foreignkey')
    op.create_foreign_key(op.f('ai_conversations_user_id_fkey'), 'ai_conversations', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_ai_conversations_id'), table_name='ai_conversations')
    op.alter_column('ai_conversations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('ai_conversations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('ai_conversations', 'task_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('ai_conversations', 'user_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_index(op.f('ix_achievements_id'), table_name='achievements')
    op.alter_column('achievements', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('display_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('avatar_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('last_login_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('xp', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('level', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('solved_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('total_submissions', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey'))
    )
    op.create_index(op.f('ix_users_xp'), 'users', ['xp'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_index(op.f('ix_users_level'), 'users', ['level'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_index(op.f('ix_discussion_votes_user_id'), table_name='discussion_votes')
    op.drop_index(op.f('ix_discussion_votes_id'), table_name='discussion_votes')
    op.drop_index(op.f('ix_discussion_votes_discussion_id'), table_name='discussion_votes')
    op.drop_table('discussion_votes')
    op.drop_index(op.f('ix_discussions_user_id'), table_name='discussions')
    op.drop_index(op.f('ix_discussions_problem_id'), table_name='discussions')
    op.drop_index(op.f('ix_discussions_id'), table_name='discussions')
    op.drop_table('discussions')
    op.drop_index(op.f('ix_profiles_xp'), table_name='profiles')
    op.drop_index(op.f('ix_profiles_username'), table_name='profiles')
    op.drop_index(op.f('ix_profiles_level'), table_name='profiles')
    op.drop_table('profiles')
    # ### end Alembic commands ###
